# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  pepe:
    description: 'random word'
    required: false
    default: 'ega'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args: |
    ${{ inputs.who-to-greet }}
    ${{ inputs.pepe }}
