name: "Hello-world"
description: "Say hello-world and record the time"
inputs:
  who-to-greet:
    description: "name of the person to attach to Hello word"
    required: true
    default: "World"
  output:
    time:
      description: "Current time"

  runs:
    using: "docker"
    image: "Dockerfile"
    args:
      - ${{ inputs.who-to-greet }}
